### ISSUE TITLE
Add CI-coverage for pytest

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/pilz_industrial_motion#289]
# Code Coverage for pytest with ROS

## Goal
Create coverage for pytest using ROS

## How is this working with unittests?

A python unittest is added to the CMakeLists.txt using
```
catkin_add_nosetests(unittest.py)
```
where the CMake-Macro is defined in [https://github.com/ros/catkin](https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/test/nosetests.cmake#L59)

here to macro checks for the environment variable `CATKIN_TEST_COVERAGE` and will enable the coverage flags

```
if("$ENV{CATKIN_TEST_COVERAGE}" STREQUAL "1")
  set(_covarg " --with-coverage")
endif()
```
[src](https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/test/nosetests.cmake#L59-L61)

## How could/should we extend this for pytest?
A python pytest is added to the CMakeLists.txt using
```
add_pytest(pytest.py)
```
where CMake-Macro is define in [https://github.com/machinekoder/ros_pytest](https://github.com/machinekoder/ros_pytest/blob/ba165ad44b854dc6839a9b249ea9b9f1bba5206d/cmake/pytest.cmake#L28)

However inside this Macro the essential part is commented out [see](https://github.com/machinekoder/ros_pytest/blob/ba165ad44b854dc6839a9b249ea9b9f1bba5206d/cmake/pytest.cmake#L51)

### Steps done
- Open PR to rosdistro for python-pytest-cover https://github.com/ros/rosdistro/pull/24929

### Next steps
- [x] Check if https://github.com/ros/rosdistro/pull/24929 is closed
- [x] Open PR for https://github.com/machinekoder/ros_pytest for coverage functionality similiar to the catkin CMake-Macro //Done: -> see machinekoder/ros_pytest/pull/6
- [x]  Ensure that machinekoder/ros_pytest/pull/6 is merged
- [ ]  ~Ensure that mikeferguson/code_coverage/pull/22 is merged~
- [x]  Ensure that mikeferguson/code_coverage/pull/23 is merged
- [x] Ensure that PR #294 is merged
- [x] Fix https://github.com/PilzDE/industrial_ci_addons/issues/1
- [x] Ensure that ros_pytest is released
- [x] Ensure that code_coverage is released

Working branch: https://github.com/PilzDE/pilz_industrial_motion/tree/feature/store_positions

**Comment by hslusarek** [comment]
I opened a draft PR  machinekoder/ros_pytest/pull/6 which should take care of the coverage for the py_test framework.
To integrate the py_test in our overall Travis-CI concept no further steps should be necessary except for the ros/rosdistro/pull/24929 which is already merged.

**Comment by hslusarek** [comment]
Currently the [mikeferguson/code_coverage#L175](https://github.com/mikeferguson/code_coverage/blob/master/cmake/Modules/CodeCoverage.cmake#L175) creates a xml file for the python coverage. For the cpp part a html is created, therefore, I suggest to also create a html report instead of a xml report for the python coverage.

Furthermore, to be able to remove the [`add_python_coverage`](https://github.com/PilzDE/pilz_industrial_motion/blob/831fce5c230a07c54e7db9f770adc8f436e1d533/pilz_robot_programming/CMakeLists.txt#L57) function from the CMakeLists.txt in `pilz_robot_programming` and to totally unify the coverage output for nosetests and pytest, some additional refinements for the python-coverage have to be made. These refinements are done in the following PR:
mikeferguson/code_coverage/pull/22

The [`add_python_coverage`](https://github.com/PilzDE/pilz_industrial_motion/blob/831fce5c230a07c54e7db9f770adc8f436e1d533/pilz_robot_programming/CMakeLists.txt#L57) cmake function is removed in PR #294.

**Comment by hslusarek** [comment]
Sequence-diagram showing how the cmake-macro [`add_code_coverage`](https://github.com/mikeferguson/code_coverage/blob/master/cmake/Modules/CodeCoverage.cmake) works.

![diag_act_code_coverage_call_sequence](https://user-images.githubusercontent.com/40654276/82799341-32944d00-9e7a-11ea-9d1d-0349343cffc7.png)
