### ISSUE TITLE
How to use pilz robot programming with Staubli robots ?

### ISSUE THREAD

**Issue by arvind1455** [PilzDE/pilz_industrial_motion#357]
I have been trying to use pilz robot programming with Staubli robots and failed eventually. So wanted to know what are the steps to use the code with Staubli robots @jschleicher

**Comment by ct2034** [comment]
Hi Kamesh. Can you please give me more detailed info on what you are trying to do. Please tell me which version you are using and send me the launch files you are using so that I can reproduce your errors. 
We can not provide tutorials for every type of robot but if your robot works with moveit, it should also work with our planner.

**Comment by rijalmadhav12** [comment]
for example panda robot which is used in moveit demo.

**Comment by rijalmadhav12** [comment]
i want to use pilz robot programming to sequence motion of panda arm that is used in moveit demo. What are the steps I need to follow. please guide me.
